// Section 11
// Random Numbers

#include <iostream>
#include <cstdlib>      // required for rand()
#include <ctime>       // required for time( )  

using namespace std;

int main() {
      
    int random_number {};
    size_t count {10};           // number of random numbers to generate
    int min {1};                  // lower bound (inclusive) 
    int max {6};                 // upper bound (inclusive)
    
    // seed the random number generator
    // If you don't seed the generator you will get the same requence random numbers every run
    
    cout << "RAND_MAX on my system is: " << RAND_MAX << endl;   //RAND_MAX depends on your system/O.S , it will be atleast 32767.
    srand(time(nullptr));      //seeding random number generator. Here we are seeding it with number generated by system time. null pointer is zero.
                                        //Different seeds will produce different sequence of numbers.
    
    for (size_t i{1}; i<=count; ++i)  {
        random_number = rand() % (max-min+1) + min;     // rand() generate a random number....rand() % (max-min+1) can give remainder between 0 to 5 only.
        cout << random_number << endl;             //So the remainder + min (ie. 1) can vary from 1 to 6 only, which is our minimum and maximum range.
    }

    cout  << endl;
    return 0;
}